export const recipeSeeds = [
  // ── BREAKFAST ────────────────────────────────────────────────────────────
  {
    name: "Overnight Oats with Berries",
    description: "High-carb breakfast perfect for bulk days",
    meal_type: "breakfast",
    cuisine: "American",
    calories: 480,
    protein_g: 28,
    carbs_g: 72,
    fat_g: 9,
    prep_time_min: 5,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Rolled oats", qty: 1, unit: "cup" },
      { name: "Greek yogurt", qty: 0.5, unit: "cup" },
      { name: "Milk", qty: 0.5, unit: "cup" },
      { name: "Protein powder", qty: 1, unit: "scoop" },
      { name: "Mixed berries", qty: 0.5, unit: "cup" },
      { name: "Honey", qty: 1, unit: "tbsp" },
    ],
    instructions: "Mix oats, yogurt, milk, and protein powder. Refrigerate overnight. Top with berries and honey before serving.",
    tags: ["bulk-friendly", "meal-prep", "high-carb"],
  },
  {
    name: "Huevos Rancheros",
    description: "Mexican breakfast with eggs, salsa, and black beans",
    meal_type: "breakfast",
    cuisine: "Mexican",
    calories: 420,
    protein_g: 26,
    carbs_g: 38,
    fat_g: 16,
    prep_time_min: 10,
    cook_time_min: 15,
    servings: 1,
    ingredients: [
      { name: "Eggs", qty: 3, unit: "large" },
      { name: "Black beans", qty: 0.5, unit: "cup" },
      { name: "Corn tortillas", qty: 2, unit: "pieces" },
      { name: "Salsa", qty: 0.25, unit: "cup" },
      { name: "Avocado", qty: 0.25, unit: "whole" },
      { name: "Cotija cheese", qty: 2, unit: "tbsp" },
    ],
    instructions: "Fry eggs sunny-side up. Warm tortillas. Layer tortillas, beans, eggs, salsa, avocado, and cheese.",
    tags: ["high-protein", "bulk-friendly"],
  },
  {
    name: "Japanese Tamagoyaki with Rice",
    description: "Sweet rolled omelette with steamed white rice",
    meal_type: "breakfast",
    cuisine: "Japanese",
    calories: 390,
    protein_g: 22,
    carbs_g: 52,
    fat_g: 8,
    prep_time_min: 10,
    cook_time_min: 10,
    servings: 1,
    ingredients: [
      { name: "Eggs", qty: 3, unit: "large" },
      { name: "Mirin", qty: 1, unit: "tbsp" },
      { name: "Soy sauce", qty: 1, unit: "tsp" },
      { name: "Sugar", qty: 1, unit: "tsp" },
      { name: "White rice", qty: 1, unit: "cup cooked" },
    ],
    instructions: "Whisk eggs with mirin, soy sauce, and sugar. Cook in layers in a rectangular pan, rolling each layer. Serve with rice.",
    tags: ["bulk-friendly", "high-carb"],
  },
  {
    name: "Greek Yogurt Parfait",
    description: "Protein-packed parfait with granola and honey",
    meal_type: "breakfast",
    cuisine: "Mediterranean",
    calories: 340,
    protein_g: 30,
    carbs_g: 40,
    fat_g: 6,
    prep_time_min: 5,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Greek yogurt (2%)", qty: 1.5, unit: "cup" },
      { name: "Granola", qty: 0.25, unit: "cup" },
      { name: "Honey", qty: 1, unit: "tbsp" },
      { name: "Strawberries", qty: 0.5, unit: "cup" },
    ],
    instructions: "Layer yogurt, granola, and berries. Drizzle with honey.",
    tags: ["quick", "cut-friendly", "high-protein"],
  },
  {
    name: "Shakshuka",
    description: "North African eggs poached in spiced tomato sauce",
    meal_type: "breakfast",
    cuisine: "North African",
    calories: 370,
    protein_g: 24,
    carbs_g: 28,
    fat_g: 18,
    prep_time_min: 5,
    cook_time_min: 20,
    servings: 1,
    ingredients: [
      { name: "Eggs", qty: 3, unit: "large" },
      { name: "Crushed tomatoes", qty: 1, unit: "cup" },
      { name: "Bell pepper", qty: 0.5, unit: "whole" },
      { name: "Onion", qty: 0.25, unit: "whole" },
      { name: "Cumin", qty: 1, unit: "tsp" },
      { name: "Paprika", qty: 1, unit: "tsp" },
      { name: "Feta cheese", qty: 2, unit: "tbsp" },
    ],
    instructions: "Sauté onion and pepper. Add tomatoes and spices, simmer 10 min. Create wells and crack eggs in. Cover and cook until set. Top with feta.",
    tags: ["cut-friendly", "high-protein"],
  },

  // ── LUNCH ────────────────────────────────────────────────────────────────
  {
    name: "Arroz con Pollo",
    description: "Latin-style chicken and rice with sofrito and spices",
    meal_type: "lunch",
    cuisine: "Latin",
    calories: 580,
    protein_g: 48,
    carbs_g: 62,
    fat_g: 12,
    prep_time_min: 15,
    cook_time_min: 40,
    servings: 2,
    ingredients: [
      { name: "Chicken thighs", qty: 1, unit: "lb" },
      { name: "Long grain white rice", qty: 1.5, unit: "cups" },
      { name: "Sofrito", qty: 3, unit: "tbsp" },
      { name: "Sazon seasoning", qty: 1, unit: "packet" },
      { name: "Chicken broth", qty: 2.5, unit: "cups" },
      { name: "Peas", qty: 0.5, unit: "cup" },
      { name: "Olives", qty: 0.25, unit: "cup" },
    ],
    instructions: "Brown chicken with sofrito and sazon. Add rice, broth, peas, and olives. Cover and simmer 25 minutes until rice absorbs liquid.",
    tags: ["bulk-friendly", "meal-prep", "high-protein", "high-carb"],
  },
  {
    name: "Thai Basil Chicken (Pad Kra Pao)",
    description: "Spicy ground chicken stir-fry with Thai basil over jasmine rice",
    meal_type: "lunch",
    cuisine: "Thai",
    calories: 520,
    protein_g: 42,
    carbs_g: 55,
    fat_g: 10,
    prep_time_min: 10,
    cook_time_min: 15,
    servings: 1,
    ingredients: [
      { name: "Ground chicken", qty: 6, unit: "oz" },
      { name: "Thai basil", qty: 1, unit: "cup" },
      { name: "Fish sauce", qty: 1, unit: "tbsp" },
      { name: "Oyster sauce", qty: 1, unit: "tbsp" },
      { name: "Garlic", qty: 3, unit: "cloves" },
      { name: "Thai chili", qty: 2, unit: "pieces" },
      { name: "Jasmine rice", qty: 1, unit: "cup cooked" },
      { name: "Egg", qty: 1, unit: "large" },
    ],
    instructions: "Stir-fry garlic and chili. Add ground chicken, cook through. Add fish sauce, oyster sauce, and basil. Serve over rice with fried egg on top.",
    tags: ["bulk-friendly", "high-protein", "quick"],
  },
  {
    name: "Korean Bibimbap",
    description: "Rice bowl with mixed vegetables, ground beef, and gochujang",
    meal_type: "lunch",
    cuisine: "Korean",
    calories: 610,
    protein_g: 38,
    carbs_g: 78,
    fat_g: 14,
    prep_time_min: 20,
    cook_time_min: 20,
    servings: 1,
    ingredients: [
      { name: "Ground beef (93/7)", qty: 5, unit: "oz" },
      { name: "White rice", qty: 1.5, unit: "cups cooked" },
      { name: "Spinach", qty: 1, unit: "cup" },
      { name: "Bean sprouts", qty: 0.5, unit: "cup" },
      { name: "Carrot", qty: 0.5, unit: "whole" },
      { name: "Egg", qty: 1, unit: "large" },
      { name: "Gochujang", qty: 1, unit: "tbsp" },
      { name: "Sesame oil", qty: 1, unit: "tsp" },
    ],
    instructions: "Season and cook beef with soy and sesame. Blanch/sauté vegetables separately. Arrange rice in bowl, top with vegetables, beef, and fried egg. Drizzle with gochujang.",
    tags: ["bulk-friendly", "high-carb"],
  },
  {
    name: "Mediterranean Chicken Bowl",
    description: "Grilled chicken with quinoa, tzatziki, and fresh vegetables",
    meal_type: "lunch",
    cuisine: "Mediterranean",
    calories: 490,
    protein_g: 44,
    carbs_g: 42,
    fat_g: 14,
    prep_time_min: 15,
    cook_time_min: 20,
    servings: 1,
    ingredients: [
      { name: "Chicken breast", qty: 6, unit: "oz" },
      { name: "Quinoa", qty: 0.75, unit: "cup cooked" },
      { name: "Cucumber", qty: 0.5, unit: "whole" },
      { name: "Cherry tomatoes", qty: 0.5, unit: "cup" },
      { name: "Tzatziki", qty: 3, unit: "tbsp" },
      { name: "Kalamata olives", qty: 8, unit: "pieces" },
      { name: "Feta", qty: 1, unit: "oz" },
      { name: "Lemon", qty: 0.5, unit: "whole" },
    ],
    instructions: "Season and grill chicken. Serve over quinoa with vegetables. Top with tzatziki, olives, and feta. Squeeze lemon over top.",
    tags: ["cut-friendly", "high-protein", "maintenance-friendly"],
  },
  {
    name: "Lemon Herb Salmon with Couscous",
    description: "Baked salmon over herbed couscous with roasted asparagus",
    meal_type: "lunch",
    cuisine: "Mediterranean",
    calories: 540,
    protein_g: 46,
    carbs_g: 48,
    fat_g: 16,
    prep_time_min: 10,
    cook_time_min: 20,
    servings: 1,
    ingredients: [
      { name: "Salmon fillet", qty: 6, unit: "oz" },
      { name: "Couscous", qty: 0.75, unit: "cup dry" },
      { name: "Asparagus", qty: 6, unit: "spears" },
      { name: "Lemon", qty: 1, unit: "whole" },
      { name: "Dill", qty: 1, unit: "tbsp" },
      { name: "Olive oil", qty: 1, unit: "tbsp" },
      { name: "Garlic", qty: 2, unit: "cloves" },
    ],
    instructions: "Bake salmon at 400°F for 15 min with lemon and dill. Roast asparagus alongside. Cook couscous per package, fluff with herb oil.",
    tags: ["cut-friendly", "high-protein", "maintenance-friendly"],
  },
  {
    name: "Chipotle-Style Burrito Bowl",
    description: "Brown rice, black beans, grilled chicken, and fresh toppings",
    meal_type: "lunch",
    cuisine: "Mexican",
    calories: 630,
    protein_g: 50,
    carbs_g: 72,
    fat_g: 12,
    prep_time_min: 15,
    cook_time_min: 25,
    servings: 1,
    ingredients: [
      { name: "Chicken breast", qty: 6, unit: "oz" },
      { name: "Brown rice", qty: 1, unit: "cup cooked" },
      { name: "Black beans", qty: 0.5, unit: "cup" },
      { name: "Corn", qty: 0.25, unit: "cup" },
      { name: "Pico de gallo", qty: 0.25, unit: "cup" },
      { name: "Romaine lettuce", qty: 1, unit: "cup" },
      { name: "Greek yogurt (as sour cream)", qty: 2, unit: "tbsp" },
      { name: "Lime", qty: 0.5, unit: "whole" },
    ],
    instructions: "Season chicken with chipotle, cumin, and garlic. Grill or pan-sear. Build bowl with rice, beans, chicken, corn, and toppings.",
    tags: ["bulk-friendly", "high-protein", "meal-prep"],
  },
  {
    name: "Teriyaki Salmon Rice Bowl",
    description: "Glazed teriyaki salmon over steamed rice with edamame",
    meal_type: "lunch",
    cuisine: "Japanese",
    calories: 570,
    protein_g: 44,
    carbs_g: 60,
    fat_g: 14,
    prep_time_min: 10,
    cook_time_min: 15,
    servings: 1,
    ingredients: [
      { name: "Salmon fillet", qty: 6, unit: "oz" },
      { name: "Soy sauce", qty: 2, unit: "tbsp" },
      { name: "Mirin", qty: 1, unit: "tbsp" },
      { name: "Honey", qty: 1, unit: "tbsp" },
      { name: "White rice", qty: 1, unit: "cup cooked" },
      { name: "Edamame", qty: 0.5, unit: "cup" },
      { name: "Sesame seeds", qty: 1, unit: "tsp" },
    ],
    instructions: "Mix soy, mirin, honey for teriyaki glaze. Pan-sear salmon and glaze in last 2 min. Serve over rice with edamame. Top with sesame seeds.",
    tags: ["bulk-friendly", "high-protein"],
  },

  // ── DINNER ───────────────────────────────────────────────────────────────
  {
    name: "Bistec Encebollado",
    description: "Cuban pan-seared steak with caramelized onions",
    meal_type: "dinner",
    cuisine: "Latin",
    calories: 520,
    protein_g: 52,
    carbs_g: 18,
    fat_g: 26,
    prep_time_min: 10,
    cook_time_min: 20,
    servings: 1,
    ingredients: [
      { name: "Sirloin steak", qty: 8, unit: "oz" },
      { name: "Yellow onion", qty: 1, unit: "large" },
      { name: "Garlic", qty: 4, unit: "cloves" },
      { name: "Lime juice", qty: 2, unit: "tbsp" },
      { name: "Cumin", qty: 1, unit: "tsp" },
      { name: "Oregano", qty: 1, unit: "tsp" },
      { name: "Olive oil", qty: 1, unit: "tbsp" },
    ],
    instructions: "Marinate steak in lime, cumin, oregano, and garlic. Pan-sear 4 min per side. Caramelize onions in same pan. Top steak with onions.",
    tags: ["cut-friendly", "high-protein", "maintenance-friendly"],
  },
  {
    name: "Chicken Tikka Masala",
    description: "Creamy Indian spiced chicken in tomato-cream sauce over rice",
    meal_type: "dinner",
    cuisine: "Indian",
    calories: 590,
    protein_g: 48,
    carbs_g: 55,
    fat_g: 18,
    prep_time_min: 20,
    cook_time_min: 30,
    servings: 2,
    ingredients: [
      { name: "Chicken breast", qty: 1, unit: "lb" },
      { name: "Plain yogurt", qty: 0.5, unit: "cup" },
      { name: "Canned tomatoes", qty: 14, unit: "oz" },
      { name: "Heavy cream", qty: 0.25, unit: "cup" },
      { name: "Onion", qty: 1, unit: "whole" },
      { name: "Garam masala", qty: 2, unit: "tsp" },
      { name: "Ginger", qty: 1, unit: "tbsp" },
      { name: "Garlic", qty: 4, unit: "cloves" },
      { name: "Basmati rice", qty: 1.5, unit: "cups cooked" },
    ],
    instructions: "Marinate chicken in yogurt and spices. Grill or broil. Make sauce with onion, tomatoes, cream, and spices. Add chicken to sauce and simmer. Serve over basmati.",
    tags: ["bulk-friendly", "meal-prep", "high-protein"],
  },
  {
    name: "Beef and Broccoli Stir-Fry",
    description: "Classic Chinese takeout-style beef with broccoli over rice",
    meal_type: "dinner",
    cuisine: "Chinese",
    calories: 560,
    protein_g: 44,
    carbs_g: 58,
    fat_g: 14,
    prep_time_min: 15,
    cook_time_min: 15,
    servings: 1,
    ingredients: [
      { name: "Flank steak", qty: 6, unit: "oz" },
      { name: "Broccoli", qty: 2, unit: "cups" },
      { name: "Soy sauce", qty: 3, unit: "tbsp" },
      { name: "Oyster sauce", qty: 1, unit: "tbsp" },
      { name: "Sesame oil", qty: 1, unit: "tsp" },
      { name: "Cornstarch", qty: 1, unit: "tbsp" },
      { name: "Ginger", qty: 1, unit: "tsp" },
      { name: "White rice", qty: 1, unit: "cup cooked" },
    ],
    instructions: "Slice beef thin, toss with cornstarch and soy. Stir-fry on high heat. Add broccoli and sauce. Serve over rice.",
    tags: ["bulk-friendly", "quick", "high-protein"],
  },
  {
    name: "Moroccan Spiced Chicken Thighs",
    description: "Oven-roasted chicken thighs with ras el hanout, chickpeas, and couscous",
    meal_type: "dinner",
    cuisine: "Moroccan",
    calories: 570,
    protein_g: 46,
    carbs_g: 50,
    fat_g: 16,
    prep_time_min: 15,
    cook_time_min: 35,
    servings: 2,
    ingredients: [
      { name: "Chicken thighs (bone-in)", qty: 4, unit: "pieces" },
      { name: "Chickpeas", qty: 1, unit: "can" },
      { name: "Couscous", qty: 1, unit: "cup dry" },
      { name: "Ras el hanout", qty: 2, unit: "tsp" },
      { name: "Cinnamon", qty: 0.5, unit: "tsp" },
      { name: "Diced tomatoes", qty: 0.5, unit: "cup" },
      { name: "Cilantro", qty: 2, unit: "tbsp" },
    ],
    instructions: "Rub chicken with spices. Roast at 425°F 30-35 min. Pan-fry chickpeas with leftover spices. Serve over couscous topped with tomatoes and cilantro.",
    tags: ["meal-prep", "bulk-friendly", "high-protein"],
  },
  {
    name: "Turkey Meatballs with Zucchini Noodles",
    description: "Lean turkey meatballs in marinara over zucchini noodles",
    meal_type: "dinner",
    cuisine: "Italian",
    calories: 420,
    protein_g: 46,
    carbs_g: 22,
    fat_g: 16,
    prep_time_min: 20,
    cook_time_min: 25,
    servings: 2,
    ingredients: [
      { name: "Ground turkey (93/7)", qty: 1, unit: "lb" },
      { name: "Zucchini", qty: 3, unit: "medium" },
      { name: "Marinara sauce", qty: 1.5, unit: "cups" },
      { name: "Egg", qty: 1, unit: "large" },
      { name: "Breadcrumbs", qty: 0.25, unit: "cup" },
      { name: "Parmesan", qty: 2, unit: "tbsp" },
      { name: "Italian seasoning", qty: 1, unit: "tbsp" },
    ],
    instructions: "Mix turkey with egg, breadcrumbs, and seasoning. Form meatballs and bake at 400°F 20 min. Spiralize zucchini, sauté briefly. Top with meatballs and marinara.",
    tags: ["cut-friendly", "high-protein", "low-carb"],
  },
  {
    name: "Black Bean Enchiladas",
    description: "Vegetarian enchiladas with black beans, corn, and cheese",
    meal_type: "dinner",
    cuisine: "Mexican",
    calories: 480,
    protein_g: 24,
    carbs_g: 68,
    fat_g: 14,
    prep_time_min: 20,
    cook_time_min: 30,
    servings: 2,
    ingredients: [
      { name: "Black beans", qty: 1, unit: "can" },
      { name: "Corn tortillas", qty: 6, unit: "pieces" },
      { name: "Enchilada sauce", qty: 1.5, unit: "cups" },
      { name: "Corn", qty: 0.5, unit: "cup" },
      { name: "Cheddar cheese", qty: 1, unit: "cup shredded" },
      { name: "Onion", qty: 0.5, unit: "whole" },
      { name: "Cumin", qty: 1, unit: "tsp" },
    ],
    instructions: "Mix beans, corn, onion, and cumin. Fill tortillas, roll and place in baking dish. Pour enchilada sauce over top, add cheese. Bake at 375°F for 25 min.",
    tags: ["bulk-friendly", "meal-prep", "vegetarian"],
  },
  {
    name: "Jerk Chicken with Rice and Peas",
    description: "Jamaican-style spiced chicken with coconut rice and kidney beans",
    meal_type: "dinner",
    cuisine: "Caribbean",
    calories: 620,
    protein_g: 50,
    carbs_g: 65,
    fat_g: 14,
    prep_time_min: 20,
    cook_time_min: 35,
    servings: 2,
    ingredients: [
      { name: "Chicken drumsticks", qty: 4, unit: "pieces" },
      { name: "Jerk seasoning", qty: 3, unit: "tbsp" },
      { name: "Long grain rice", qty: 1.5, unit: "cups" },
      { name: "Kidney beans", qty: 1, unit: "can" },
      { name: "Coconut milk", qty: 0.75, unit: "cup" },
      { name: "Scallions", qty: 4, unit: "stalks" },
      { name: "Thyme", qty: 2, unit: "sprigs" },
    ],
    instructions: "Marinate chicken in jerk seasoning overnight (or 1 hr). Grill or bake at 425°F. Cook rice in coconut milk with beans, scallions, and thyme.",
    tags: ["bulk-friendly", "meal-prep", "high-protein"],
  },
  {
    name: "Vietnamese Pho (Chicken)",
    description: "Light aromatic chicken broth with rice noodles and fresh herbs",
    meal_type: "dinner",
    cuisine: "Vietnamese",
    calories: 430,
    protein_g: 38,
    carbs_g: 48,
    fat_g: 6,
    prep_time_min: 15,
    cook_time_min: 30,
    servings: 1,
    ingredients: [
      { name: "Chicken breast", qty: 5, unit: "oz" },
      { name: "Rice noodles", qty: 3, unit: "oz" },
      { name: "Chicken broth", qty: 3, unit: "cups" },
      { name: "Star anise", qty: 2, unit: "pieces" },
      { name: "Cinnamon stick", qty: 1, unit: "piece" },
      { name: "Bean sprouts", qty: 0.5, unit: "cup" },
      { name: "Fresh basil", qty: 0.25, unit: "cup" },
      { name: "Lime", qty: 1, unit: "whole" },
      { name: "Fish sauce", qty: 1, unit: "tbsp" },
    ],
    instructions: "Simmer broth with star anise and cinnamon 20 min. Add sliced chicken. Cook noodles separately. Serve broth over noodles, top with sprouts, basil, and lime.",
    tags: ["cut-friendly", "low-fat"],
  },
  {
    name: "Greek Chicken Souvlaki",
    description: "Grilled chicken skewers with pita, tzatziki, and Greek salad",
    meal_type: "dinner",
    cuisine: "Greek",
    calories: 510,
    protein_g: 44,
    carbs_g: 42,
    fat_g: 16,
    prep_time_min: 20,
    cook_time_min: 15,
    servings: 1,
    ingredients: [
      { name: "Chicken breast", qty: 6, unit: "oz" },
      { name: "Whole wheat pita", qty: 1, unit: "piece" },
      { name: "Tzatziki", qty: 3, unit: "tbsp" },
      { name: "Tomato", qty: 1, unit: "medium" },
      { name: "Cucumber", qty: 0.5, unit: "whole" },
      { name: "Red onion", qty: 0.25, unit: "whole" },
      { name: "Lemon", qty: 1, unit: "whole" },
      { name: "Oregano", qty: 1, unit: "tbsp" },
      { name: "Olive oil", qty: 1, unit: "tbsp" },
    ],
    instructions: "Cube chicken, marinate in lemon, olive oil, and oregano. Skewer and grill 12-15 min. Serve in pita with tzatziki and Greek salad.",
    tags: ["maintenance-friendly", "high-protein"],
  },

  // ── SNACKS ───────────────────────────────────────────────────────────────
  {
    name: "Cottage Cheese & Pineapple",
    description: "High-protein snack with cottage cheese and fresh pineapple",
    meal_type: "snack",
    cuisine: "American",
    calories: 220,
    protein_g: 24,
    carbs_g: 26,
    fat_g: 2,
    prep_time_min: 2,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Cottage cheese (low-fat)", qty: 1, unit: "cup" },
      { name: "Pineapple chunks", qty: 0.5, unit: "cup" },
    ],
    instructions: "Combine in a bowl. Serve cold.",
    tags: ["cut-friendly", "high-protein", "quick"],
  },
  {
    name: "Rice Cakes with Almond Butter",
    description: "Light carb snack with healthy fats",
    meal_type: "snack",
    cuisine: "American",
    calories: 280,
    protein_g: 8,
    carbs_g: 34,
    fat_g: 12,
    prep_time_min: 2,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Rice cakes", qty: 3, unit: "pieces" },
      { name: "Almond butter", qty: 2, unit: "tbsp" },
      { name: "Banana", qty: 0.5, unit: "whole" },
    ],
    instructions: "Spread almond butter on rice cakes. Top with banana slices.",
    tags: ["quick", "bulk-friendly"],
  },
  {
    name: "Edamame with Sea Salt",
    description: "Steamed edamame with flaky sea salt",
    meal_type: "snack",
    cuisine: "Japanese",
    calories: 188,
    protein_g: 16,
    carbs_g: 14,
    fat_g: 8,
    prep_time_min: 1,
    cook_time_min: 5,
    servings: 1,
    ingredients: [
      { name: "Edamame (in shell)", qty: 1.5, unit: "cups" },
      { name: "Sea salt", qty: 0.5, unit: "tsp" },
    ],
    instructions: "Boil or microwave edamame. Drain and sprinkle with sea salt.",
    tags: ["cut-friendly", "quick", "high-protein"],
  },
  {
    name: "Turkey Roll-Ups",
    description: "Lean turkey slices rolled with avocado and veggies",
    meal_type: "snack",
    cuisine: "American",
    calories: 240,
    protein_g: 22,
    carbs_g: 8,
    fat_g: 14,
    prep_time_min: 5,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Deli turkey (low-sodium)", qty: 4, unit: "oz" },
      { name: "Avocado", qty: 0.25, unit: "whole" },
      { name: "Cucumber", qty: 0.5, unit: "whole" },
      { name: "Mustard", qty: 1, unit: "tsp" },
    ],
    instructions: "Lay turkey slices flat. Spread avocado and mustard. Place cucumber strips and roll up.",
    tags: ["cut-friendly", "quick", "low-carb", "high-protein"],
  },
  {
    name: "Hummus & Veggie Plate",
    description: "Classic hummus with fresh cut vegetables",
    meal_type: "snack",
    cuisine: "Middle Eastern",
    calories: 230,
    protein_g: 8,
    carbs_g: 28,
    fat_g: 10,
    prep_time_min: 5,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Hummus", qty: 4, unit: "tbsp" },
      { name: "Bell pepper", qty: 1, unit: "whole" },
      { name: "Carrot", qty: 1, unit: "medium" },
      { name: "Cucumber", qty: 0.5, unit: "whole" },
      { name: "Celery", qty: 2, unit: "stalks" },
    ],
    instructions: "Slice all vegetables into sticks. Serve with hummus for dipping.",
    tags: ["maintenance-friendly", "quick", "vegetarian"],
  },

  // ── SHAKES ───────────────────────────────────────────────────────────────
  {
    name: "Post-Workout Mass Shake",
    description: "High-calorie protein shake for post-training recovery on bulk",
    meal_type: "shake",
    cuisine: "American",
    calories: 680,
    protein_g: 52,
    carbs_g: 88,
    fat_g: 12,
    prep_time_min: 5,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Whole milk", qty: 1.5, unit: "cups" },
      { name: "Whey protein powder", qty: 2, unit: "scoops" },
      { name: "Banana", qty: 1, unit: "large" },
      { name: "Oats", qty: 0.5, unit: "cup" },
      { name: "Peanut butter", qty: 2, unit: "tbsp" },
      { name: "Honey", qty: 1, unit: "tbsp" },
    ],
    instructions: "Blend all ingredients until smooth. Consume within 30 minutes post-workout.",
    tags: ["bulk-friendly", "high-protein", "post-workout", "quick"],
  },
  {
    name: "Lean Cut Protein Shake",
    description: "Low-calorie high-protein shake for cut phases",
    meal_type: "shake",
    cuisine: "American",
    calories: 280,
    protein_g: 44,
    carbs_g: 18,
    fat_g: 3,
    prep_time_min: 3,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Water or unsweetened almond milk", qty: 1.5, unit: "cups" },
      { name: "Whey isolate protein powder", qty: 2, unit: "scoops" },
      { name: "Frozen strawberries", qty: 0.5, unit: "cup" },
      { name: "Ice", qty: 1, unit: "cup" },
    ],
    instructions: "Blend all ingredients until smooth.",
    tags: ["cut-friendly", "high-protein", "low-fat", "quick"],
  },
  {
    name: "Green Power Smoothie",
    description: "Spinach, banana, and protein powder — nutrient-dense maintenance shake",
    meal_type: "shake",
    cuisine: "American",
    calories: 370,
    protein_g: 32,
    carbs_g: 48,
    fat_g: 6,
    prep_time_min: 5,
    cook_time_min: 0,
    servings: 1,
    ingredients: [
      { name: "Spinach", qty: 2, unit: "cups" },
      { name: "Banana", qty: 1, unit: "medium" },
      { name: "Protein powder (vanilla)", qty: 1, unit: "scoop" },
      { name: "Almond milk", qty: 1, unit: "cup" },
      { name: "Chia seeds", qty: 1, unit: "tbsp" },
      { name: "Frozen mango", qty: 0.5, unit: "cup" },
    ],
    instructions: "Blend spinach and almond milk first. Add remaining ingredients and blend until smooth.",
    tags: ["maintenance-friendly", "high-protein", "quick"],
  },

  // ── EXTRA HIGH-VOLUME BULK MEALS ─────────────────────────────────────────
  {
    name: "Chicken Fried Rice",
    description: "High-calorie fried rice with chicken, eggs, and vegetables",
    meal_type: "lunch",
    cuisine: "Chinese",
    calories: 680,
    protein_g: 48,
    carbs_g: 82,
    fat_g: 14,
    prep_time_min: 10,
    cook_time_min: 15,
    servings: 2,
    ingredients: [
      { name: "Day-old white rice", qty: 2, unit: "cups cooked" },
      { name: "Chicken breast", qty: 8, unit: "oz" },
      { name: "Eggs", qty: 2, unit: "large" },
      { name: "Frozen peas and carrots", qty: 0.5, unit: "cup" },
      { name: "Soy sauce", qty: 3, unit: "tbsp" },
      { name: "Sesame oil", qty: 1, unit: "tsp" },
      { name: "Garlic", qty: 2, unit: "cloves" },
      { name: "Green onion", qty: 2, unit: "stalks" },
    ],
    instructions: "Cook chicken, set aside. Scramble eggs in wok. Add rice, break up clumps. Add vegetables, soy sauce, sesame oil. Toss everything together with chicken.",
    tags: ["bulk-friendly", "meal-prep", "high-carb", "high-protein"],
  },
  {
    name: "Pasta Bolognese",
    description: "Classic Italian meat sauce over penne — ideal bulk meal",
    meal_type: "dinner",
    cuisine: "Italian",
    calories: 720,
    protein_g: 48,
    carbs_g: 88,
    fat_g: 16,
    prep_time_min: 15,
    cook_time_min: 40,
    servings: 2,
    ingredients: [
      { name: "Lean ground beef (93/7)", qty: 12, unit: "oz" },
      { name: "Penne pasta", qty: 3, unit: "oz dry" },
      { name: "Crushed tomatoes", qty: 28, unit: "oz can" },
      { name: "Onion", qty: 1, unit: "whole" },
      { name: "Garlic", qty: 4, unit: "cloves" },
      { name: "Carrots", qty: 1, unit: "whole" },
      { name: "Celery", qty: 2, unit: "stalks" },
      { name: "Parmesan", qty: 2, unit: "tbsp" },
    ],
    instructions: "Brown beef with mirepoix. Add tomatoes, simmer 30 min. Cook pasta al dente. Combine, top with parmesan.",
    tags: ["bulk-friendly", "meal-prep", "high-carb"],
  },
  {
    name: "Sweet Potato & Chicken Hash",
    description: "Diced sweet potato, chicken, and peppers — great cook-day meal prep",
    meal_type: "lunch",
    cuisine: "American",
    calories: 510,
    protein_g: 44,
    carbs_g: 56,
    fat_g: 10,
    prep_time_min: 15,
    cook_time_min: 25,
    servings: 2,
    ingredients: [
      { name: "Chicken breast", qty: 12, unit: "oz" },
      { name: "Sweet potatoes", qty: 2, unit: "medium" },
      { name: "Bell peppers", qty: 2, unit: "whole" },
      { name: "Onion", qty: 1, unit: "whole" },
      { name: "Garlic powder", qty: 1, unit: "tsp" },
      { name: "Smoked paprika", qty: 1, unit: "tsp" },
      { name: "Olive oil", qty: 1, unit: "tbsp" },
    ],
    instructions: "Dice all ingredients. Roast sweet potatoes at 400°F 20 min. Sauté chicken with peppers and onion. Combine everything with spices.",
    tags: ["meal-prep", "bulk-friendly", "cook-day"],
  },
  {
    name: "Lentil Dal",
    description: "Spiced Indian red lentils — high-protein vegetarian option",
    meal_type: "dinner",
    cuisine: "Indian",
    calories: 420,
    protein_g: 24,
    carbs_g: 62,
    fat_g: 8,
    prep_time_min: 10,
    cook_time_min: 30,
    servings: 2,
    ingredients: [
      { name: "Red lentils", qty: 1, unit: "cup dry" },
      { name: "Coconut milk (light)", qty: 0.5, unit: "cup" },
      { name: "Diced tomatoes", qty: 1, unit: "can" },
      { name: "Onion", qty: 1, unit: "whole" },
      { name: "Turmeric", qty: 1, unit: "tsp" },
      { name: "Cumin", qty: 1, unit: "tsp" },
      { name: "Garam masala", qty: 1, unit: "tsp" },
      { name: "Basmati rice", qty: 1.5, unit: "cups cooked" },
    ],
    instructions: "Sauté onion with spices. Add lentils, tomatoes, coconut milk, and water. Simmer 25 min until thick. Serve over basmati.",
    tags: ["bulk-friendly", "vegetarian", "meal-prep", "high-carb"],
  },
  {
    name: "Peruvian Lomo Saltado",
    description: "Stir-fried beef with tomatoes, peppers, and soy sauce over rice and fries",
    meal_type: "dinner",
    cuisine: "Peruvian",
    calories: 660,
    protein_g: 46,
    carbs_g: 72,
    fat_g: 18,
    prep_time_min: 20,
    cook_time_min: 20,
    servings: 2,
    ingredients: [
      { name: "Sirloin steak", qty: 12, unit: "oz" },
      { name: "White rice", qty: 1.5, unit: "cups cooked" },
      { name: "Frozen french fries", qty: 1, unit: "cup baked" },
      { name: "Tomatoes", qty: 2, unit: "medium" },
      { name: "Yellow chili (aji amarillo)", qty: 1, unit: "whole" },
      { name: "Red onion", qty: 1, unit: "large" },
      { name: "Soy sauce", qty: 2, unit: "tbsp" },
      { name: "Cilantro", qty: 2, unit: "tbsp" },
    ],
    instructions: "Stir-fry beef strips on high heat. Add onion, tomatoes, and chili. Deglaze with soy sauce. Toss in fries. Serve over rice with cilantro.",
    tags: ["bulk-friendly", "high-carb", "high-protein"],
  },
  {
    name: "Tuna Sushi Bowl",
    description: "Deconstructed sushi with sushi rice, tuna, avocado, and soy",
    meal_type: "lunch",
    cuisine: "Japanese",
    calories: 490,
    protein_g: 40,
    carbs_g: 58,
    fat_g: 10,
    prep_time_min: 15,
    cook_time_min: 20,
    servings: 1,
    ingredients: [
      { name: "Sushi-grade tuna", qty: 5, unit: "oz" },
      { name: "Sushi rice", qty: 1, unit: "cup cooked" },
      { name: "Avocado", qty: 0.25, unit: "whole" },
      { name: "Cucumber", qty: 0.5, unit: "whole" },
      { name: "Soy sauce", qty: 2, unit: "tbsp" },
      { name: "Rice vinegar", qty: 1, unit: "tbsp" },
      { name: "Sesame seeds", qty: 1, unit: "tsp" },
      { name: "Nori sheets", qty: 2, unit: "pieces" },
    ],
    instructions: "Season cooked rice with rice vinegar and salt. Slice tuna and avocado. Build bowl and top with soy, sesame seeds, and nori strips.",
    tags: ["maintenance-friendly", "high-protein"],
  },
  {
    name: "Ethiopian Doro Wat",
    description: "Spiced chicken stew in berbere sauce with injera",
    meal_type: "dinner",
    cuisine: "Ethiopian",
    calories: 540,
    protein_g: 44,
    carbs_g: 48,
    fat_g: 16,
    prep_time_min: 20,
    cook_time_min: 45,
    servings: 2,
    ingredients: [
      { name: "Chicken thighs", qty: 1, unit: "lb" },
      { name: "Berbere spice blend", qty: 2, unit: "tbsp" },
      { name: "Red onion", qty: 2, unit: "large" },
      { name: "Niter kibbeh (clarified butter)", qty: 2, unit: "tbsp" },
      { name: "Hard-boiled eggs", qty: 2, unit: "large" },
      { name: "Injera or flatbread", qty: 2, unit: "pieces" },
    ],
    instructions: "Caramelize onions in niter kibbeh 30 min. Add berbere and chicken. Simmer 30 min. Add scored hard-boiled eggs. Serve over injera.",
    tags: ["high-protein", "meal-prep"],
  },
  {
    name: "Carne Asada Tacos",
    description: "Grilled marinated steak in corn tortillas with fresh salsa",
    meal_type: "dinner",
    cuisine: "Mexican",
    calories: 560,
    protein_g: 44,
    carbs_g: 52,
    fat_g: 16,
    prep_time_min: 20,
    cook_time_min: 15,
    servings: 2,
    ingredients: [
      { name: "Skirt steak", qty: 12, unit: "oz" },
      { name: "Corn tortillas", qty: 6, unit: "pieces" },
      { name: "Lime juice", qty: 3, unit: "tbsp" },
      { name: "Cilantro", qty: 0.25, unit: "cup" },
      { name: "White onion", qty: 0.5, unit: "whole" },
      { name: "Jalapeño", qty: 1, unit: "whole" },
      { name: "Garlic", qty: 3, unit: "cloves" },
      { name: "Orange juice", qty: 2, unit: "tbsp" },
    ],
    instructions: "Marinate steak in citrus, garlic, and cilantro 1+ hr. Grill on high heat 3-4 min per side. Rest and slice thin. Serve in warm tortillas with diced onion and cilantro.",
    tags: ["bulk-friendly", "high-protein"],
  },
  {
    name: "Pad Thai with Shrimp",
    description: "Classic Thai rice noodles with shrimp, egg, and peanuts",
    meal_type: "dinner",
    cuisine: "Thai",
    calories: 540,
    protein_g: 38,
    carbs_g: 66,
    fat_g: 12,
    prep_time_min: 15,
    cook_time_min: 15,
    servings: 1,
    ingredients: [
      { name: "Rice noodles", qty: 3, unit: "oz dry" },
      { name: "Shrimp (peeled)", qty: 5, unit: "oz" },
      { name: "Eggs", qty: 2, unit: "large" },
      { name: "Tamarind paste", qty: 2, unit: "tbsp" },
      { name: "Fish sauce", qty: 1, unit: "tbsp" },
      { name: "Palm sugar", qty: 1, unit: "tbsp" },
      { name: "Bean sprouts", qty: 0.5, unit: "cup" },
      { name: "Peanuts", qty: 2, unit: "tbsp" },
      { name: "Lime", qty: 1, unit: "whole" },
    ],
    instructions: "Soak noodles in warm water 30 min. Stir-fry shrimp, push aside, scramble eggs. Add noodles and sauce (tamarind, fish sauce, sugar). Toss in sprouts. Serve with peanuts and lime.",
    tags: ["bulk-friendly", "high-protein", "high-carb"],
  },
  {
    name: "Nigerian Jollof Rice with Chicken",
    description: "West African tomato-based rice with spiced grilled chicken",
    meal_type: "dinner",
    cuisine: "West African",
    calories: 640,
    protein_g: 50,
    carbs_g: 70,
    fat_g: 14,
    prep_time_min: 20,
    cook_time_min: 50,
    servings: 2,
    ingredients: [
      { name: "Chicken pieces", qty: 1, unit: "lb" },
      { name: "Long grain rice", qty: 1.5, unit: "cups" },
      { name: "Tomato paste", qty: 3, unit: "tbsp" },
      { name: "Canned tomatoes", qty: 14, unit: "oz" },
      { name: "Bell peppers", qty: 2, unit: "whole" },
      { name: "Onion", qty: 1, unit: "large" },
      { name: "Chicken broth", qty: 2, unit: "cups" },
      { name: "Thyme", qty: 1, unit: "tsp" },
      { name: "Curry powder", qty: 1, unit: "tsp" },
    ],
    instructions: "Blend tomatoes, peppers, and onion. Fry paste 20 min. Add broth, rice, and spices. Cover and cook 30 min. Serve with grilled spiced chicken.",
    tags: ["bulk-friendly", "meal-prep", "high-carb", "high-protein"],
  },
];
